### ISSUE TITLE
[Bug?]: version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

### ISSUE THREAD

**Issue by While-Shark** [KonataDev/Lagrange.Core#193]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

4a59d8b85550e0b6f80e78a7ed09d063539a29a2

### 运行环境

其它（请在下方说明）

### 运行架构

x64

### 连接方式

None

### 重现步骤

系统是群晖DSM918
Linux  4.4.59+ #25426 SMP PREEMPT Tue May 12 04:54:55 CST 2020 x86_64 GNU/Linux synology_apollolake_918+
用的安装包是Lagrange.OneBot_linux-x64_8.0，压缩后运行，说是没找到以下文件

relocation error: ./Lagrange.OneBot: symbol _ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

### 期望的结果是什么？

能正常运行

### 实际的结果是什么？

能正常运行

### 日志记录（可选）

```Shell
./Lagrange.OneBot: /lib/libstdc++.so.6: no version information available (required by ./Lagrange.OneBot)
./Lagrange.OneBot: /lib/libstdc++.so.6: no version information available (required by ./Lagrange.OneBot)
./Lagrange.OneBot: /lib/libstdc++.so.6: no version information available (required by ./Lagrange.OneBot)
./Lagrange.OneBot: /lib/libstdc++.so.6: no version information available (required by ./Lagrange.OneBot)
./Lagrange.OneBot: /lib/libstdc++.so.6: no version information available (required by ./Lagrange.OneBot)
./Lagrange.OneBot: /lib/libstdc++.so.6: no version information available (required by ./Lagrange.OneBot)
./Lagrange.OneBot: /lib/libstdc++.so.6: no version information available (required by ./Lagrange.OneBot)
./Lagrange.OneBot: /lib/libstdc++.so.6: no version information available (required by ./Lagrange.OneBot)
./Lagrange.OneBot: /lib/libstdc++.so.6: no version information available (required by ./Lagrange.OneBot)
./Lagrange.OneBot: /lib/libstdc++.so.6: no version information available (required by ./Lagrange.OneBot)
./Lagrange.OneBot: /lib/libstdc++.so.6: no version information available (required by ./Lagrange.OneBot)
./Lagrange.OneBot: relocation error: ./Lagrange.OneBot: symbol _ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

**Comment by DarkCWK** [comment]
群晖缺少部分运行所需的库, 你可以使用 Docker 运行

**Comment by While-Shark** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by synodriver** [comment]
可以跑，群晖安装docker，打开ssh，按照文档docker的步骤实现，一定要ssh操作docker，群晖的webui不能对docker做精细操作
