### ISSUE TITLE
[Feature Request]: 私聊文件的消息事件。

### ISSUE THREAD

**Issue by scarletborder** [KonataDev/Lagrange.Core#211]
### Lagrange项目

OneBot

### 新需求内容

在接受到私聊文件时向下游应用段发送消息事件  
目前在收到私聊文件时，lagr.onebot.exe可以正常收到信息（包括了文件链接）但是并没有正常的向websocket服务端发送事件
![msg_ws_server](https://github.com/KonataDev/Lagrange.Core/assets/113498782/79af9646-0c3e-4baf-ae70-87fa88b2dc32)
![图片](https://github.com/KonataDev/Lagrange.Core/assets/20531116/7c55e3f1-a7ba-4056-bafa-f4740effe76f)

**Comment by Linwenxuan05** [comment]
12348152de89e84f3c8f050a2116f631b963cd18
