### ISSUE TITLE
[Bug]: get_friend_msg_history 参数 count 不起作用

### ISSUE THREAD

**Issue by lava081** [KonataDev/Lagrange.Core#212]
### Lagrange项目

OneBot

### 新需求内容

get_friend_msg_history接口能否支持传入类似get_group_msg_history接口的count用于指定获取的历史记录条数，目前好像是固定获取20条
`{ user_id, message_id, count }`

**Comment by lava081** [comment]
使用最新build测试的时候这个参数貌似并没有起作用，传入1时还是获取了多条消息

**Comment by lava081** [comment]
谢谢

**Comment by lava081** [comment]
猜测需要将`Lagrange.OneBot\Core\Operation\Message\GetFriendMessageHistoryOperation.cs`第28行`if (await context.GetRoamMessage(chain, 20) is { } results)`改为`if (await context.GetRoamMessage(chain, history.Count) is { } results)`

**Comment by DarkCWK** [comment]
> 猜测需要将`Lagrange.OneBot\Core\Operation\Message\GetFriendMessageHistoryOperation.cs`第28行`if (await context.GetRoamMessage(chain, 20) is { } results)`改为`if (await context.GetRoamMessage(chain, history.Count) is { } results)`

是这里的问题, 已经修复, 等待 PR 合并

**Comment by lava081** [comment]
谢谢

**Comment by DarkCWK** [comment]
这还没合并呢 (
