### ISSUE TITLE
[Bug]: 合并转发消息里的图片有很多群友点开显示加载失败

### ISSUE THREAD

**Issue by Q1351998764** [KonataDev/Lagrange.Core#214]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

其它（请在下方说明）

### 所使用/依赖的Lagrange项目对应的commit

最新版的release

### 运行环境

Linux

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

发送合并转发消息后，有部分群友点开显示加载失败。但是如果再把机器人发送的合并消息手动转发一次，就会恢复正常，所有人都能看到图片内容。

### 期望的结果是什么？

期望机器人发送的合并转发消息所有人都能正常加载里面的图片。

### 实际的结果是什么？

![51ea834bf9d0800f17a5015a8f777f26](https://github.com/KonataDev/Lagrange.Core/assets/57926506/a62a4261-c655-4525-9c05-c3e779ed7f68)
很多群友点开是这样。

**Comment by lava081** [comment]
像是客户端版本过低问题，查看机器人发送的视频时也有类似现象

**Comment by Q1351998764** [comment]
> 像是客户端版本过低问题，查看机器人发送的视频时也有类似现象

我有两个朋友，手机QQ版本都是9.0.25，他俩都是加载失败，我QQ版本9.0.15，反而可以正常加载。
