### ISSUE TITLE
[Bug?]: 使用get_stranger_info返回为None

### ISSUE THREAD

**Issue by nikissXI** [KonataDev/Lagrange.Core#218]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

0e95ae8

### 运行环境

Linux

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

使用
user_data = await bot.get_stranger_info(user_id=2499635071)
和
user_data = await bot.get_stranger_info(user_id=2780948397)

user_data返回为None，我用电脑和手机查这两个qq都是有信息的，我没加这两个人的好友

### 期望的结果是什么？

能正确返回陌生人信息

### 实际的结果是什么？

返回None

**Comment by DarkCWK** [comment]
与 #48 问题一致, 目前 `get_stranger_info` 只是从缓存的群成员中获取
