### ISSUE TITLE
[Bug]: 使用send_private_msg返回的message_id无法请求get_msg

### ISSUE THREAD

**Issue by lava081** [KonataDev/Lagrange.Core#219]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

0e95ae83cb4961490a25a03a546dd0a1235d9b47

### 运行环境

Linux

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

通过send_private_msg接口给好友发送一条消息，并获取到该条消息返回的message_id。使用message_id请求get_msg

### 期望的结果是什么？

返回该条消息的相关信息

### 实际的结果是什么？

不成功

### 简单的复现代码/链接（可选）

`await Bot[e.self_id].sendApi('get_msg',{ message_id: 692096847 })`

### 补充说明（可选）

在测试中通过引用获取的使用机器人账号人工发出的私聊消息的message_id可以用于正常请求get_msg，send_group_msg返回的message_id也可以用于正常请求get_msg，只有机器人发出的私聊消息的详情无法通过返回的message_id获得，也无法通过引用获得

**Comment by DarkCWK** [comment]
复现成功, 疑似发消息时没有将消息录入数据库

**Comment by DarkCWK** [comment]
还有一个原因是 #220

**Comment by DarkCWK** [comment]
The repository owner said that bots shouldn't have messages of their own to send.

**Comment by lava081** [comment]
即使在appsettings.json中关闭IgnoreSelf依旧请求不到

**Comment by Linwenxuan05** [comment]
因为私聊本来就收不到 等我修吧

岩浆 ***@***.***> 于 2024年3月21日周四 13:35写道：
