### ISSUE TITLE
[Bug]: `get_msg` can't get the `sender` of a private chat message.

### ISSUE THREAD

**Issue by DarkCWK** [KonataDev/Lagrange.Core#220]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

0e95ae8

### 运行环境

Windows

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

Use `get_msg` to get a private chat message.

### 期望的结果是什么？

`Echo` with the correct `sender`.
```json
{
    "status": "ok",
    "retcode": 0,
    "data": {
        "time": 1710878573,
        "message_type": "private",
        "message_id": -1814915305,
        "real_id": -1814915305,
        "sender": { "user_id": 1234567890, "nickname": "SenderName", "sex": "unknown" },
        "message": [{ "type": "text", "data": { "text": "1234" } }]
    },
    "echo": null
}
```

### 实际的结果是什么？

The `sender` in `Echo` is the default.
```json
{
    "status": "ok",
    "retcode": 0,
    "data": {
        "time": 1710878573,
        "message_type": "private",
        "message_id": -1814915305,
        "real_id": -1814915305,
        "sender": { "user_id": 0, "nickname": "", "sex": "unknown" },
        "message": [{ "type": "text", "data": { "text": "1234" } }]
    },
    "echo": null
}
```

### 补充说明（可选）

The reason is that the `LiteDatabase` query did not succeed in getting the `FriendInfo`

This is because the `FriendInfo` attribute lacks a getter

The logic error in `GetMessageOperation.cs#L23-L25` should be corrected to use `FriendInfo` instead of `GroupMemberInfo` when `chain.GroupMemberInfo == null`

**Comment by Linwenxuan05** [comment]
草 一会修理
