### ISSUE TITLE
[Bug?]: 撤回消息的id和接收消息的id不一样

### ISSUE THREAD

**Issue by nimeng1299** [KonataDev/Lagrange.Core#226]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

Core

### 所使用/依赖的Lagrange项目对应的commit

762ee4b

### 运行环境

Windows

### 运行架构

x64

### 连接方式

None

### 重现步骤

bot.Invoker.OnGroupRecallEvent += async (_, @event) =>
{
    uint groupuin = @event.GroupUin;
    uint senduin = @event.AuthorUin;
    var MessageId = CalcMessageHash(@event.Random, @event.Sequence);
    var OperatorId = @event.OperatorUin;
    Console.WriteLine("{0}-{1}-{2}-{3}", groupuin.ToString(), senduin, MessageId, OperatorId); 
   }
   
public static int CalcMessageHash(uint random, uint seq)
{
    var messageId = BitConverter.GetBytes(random);
    var sequence = BitConverter.GetBytes(seq);

    byte[] id = [messageId[0], messageId[1], sequence[0], sequence[1]];
    return BitConverter.ToInt32(id.AsSpan());
}

### 期望的结果是什么？

撤回消息的id和接收消息的id一样

### 实际的结果是什么？

撤回消息的id和接收消息的id不一样

### 补充说明（可选）

在onebot里抄的源码
```
        bot.Invoker.OnGroupRecallEvent += async (_, @event) =>
        {
            logger.LogInformation(@event.ToString());
            await service.SendJsonAsync(new OneBotGroupRecall(bot.BotUin)
            {
                GroupId = @event.GroupUin,
                UserId = @event.AuthorUin,
                MessageId = MessageRecord.CalcMessageHash(@event.Random, @event.Sequence),
                OperatorId = @event.OperatorUin
            });
        };
```
`public static int CalcMessageHash(uint random, uint seq)`也是onebot里面的，但是这里的messageid是int，而接收消息获取到的id是ulong，这两类型也不一样

**Comment by Linwenxuan05** [comment]
这是一个很恶心的故事
因为OneBot的标准要求我提供一个int32的MessageId
而腾讯给的MessageId是个ulong（0x10000000 << 32 | msgRandom)
所以MessageId实际上是个这俩玩意算出来的

**Comment by nimeng1299** [comment]
> 这是一个很恶心的故事 因为OneBot的标准要求我提供一个int32的MessageId 而腾讯给的MessageId是个ulong（0x10000000 << 32 | msgRandom) 所以MessageId实际上是个这俩玩意算出来的

我看了下`MessageChain`的构造，确实是`(0x10000000ul << 32) | (uint)Random.Shared.Next(100000000, int.MaxValue)`
但我把`MessageId = MessageRecord.CalcMessageHash(@event.Random, @event.Sequence)`改成了`ulong MessageId = (0x10000000ul << 32) | @event.Random;`结果还是不对，
原本的消息id是72057595122272351，撤回接收到的Random是1084344415，计算到的id是1152921505691191391

**Comment by Linwenxuan05** [comment]
那有可能只是我写炸了 一会看看

**Comment by Linwenxuan05** [comment]
试了一下 无法复现

**Comment by nimeng1299** [comment]
奇怪了，我这边是稳定触发

会不会是`ulong MessageId = (0x10000000ul << 32) | @event.Random;`这里写错了

|  id   | ramdon  |撤回计算的id|
|  :----:  | :----:  |:----:|
| 72057595418099305  | 1380171369 |1152921505987018345|
| 72057595277608954  | 1239681018 |1152921505846527994|

**Comment by nimeng1299** [comment]
实验结果：
`ulong MessageId = (72057594037927936ul) | @event.Random;`才是对的
有点神奇
