### ISSUE TITLE
[Bug?]: 发送视频大小显示为150B

### ISSUE THREAD

**Issue by lava081** [KonataDev/Lagrange.Core#237]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

1c0f7bf77e332e842d1b9c2eb9456f218c9968c2

### 运行环境

Linux

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

通过url发送视频
视频链接(有时效，可能需要重新获取)：https://cn-gdst-cm-01-14.bilivideo.com/upgcxcode/40/47/1385884740/1385884740-1-192.mp4?e=ig8euxZM2rNcNbRVhzdVhwdlhWdzhwdVhoNvNC8BqJIzNbfq9rVEuxTEnE8L5F6VnEsSTx0vkX8fqJeYTj_lta53NCM=&uipk=5&nbs=1&deadline=1711164778&gen=playurlv2&os=bcache&oi=1866199750&trid=000028d6edb7a43c42878c12b859b4c2e65bT&mid=359345732&platform=html5&upsig=8e9851ceb672d642696b62ee9e5a5e48&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&cdnid=6873&bvc=vod&nettype=0&bw=103889&orderid=0,1&buvid=&build=0&mobi_app=&f=T_0_0&logo=80000000

### 期望的结果是什么？

发送一个时长51秒，分辨率1280 × 720的视频

### 实际的结果是什么？

发送一个大小150B，分辨率1920 × 1080的无法播放的视频

### 简单的复现代码/链接（可选）

```C#
const response = await fetch(`https://api.bilibili.com/x/player/playurl?bvid=BV1pi4y167RU&cid=1385884740&qn=120&fnval=129&fourk=1&type=mp4&platform=html5&high_quality=1`, {
            method: 'get',
            headers: {
              'Cookie': cookie,
              'Referer': 'https://www.bilibili.com/',
              'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36'
            }
          });  // 获取视频详情
        const obj = await response.json();
        const video_url = obj.data.durl[0].url;  // 获取视频直链
        await this.reply(segment.video(video_url));  // 不缓存直接递url
```

**Comment by DarkCWK** [comment]
目前对 video 没有支持

**Comment by lava081** [comment]
我看Video绿了，别的短视频也能正常发了(

**Comment by Linwenxuan05** [comment]
视频不太能支持
