### ISSUE TITLE
[Feature Request]: 希望对踢出事件进行一些完善

### ISSUE THREAD

**Issue by bugtower100** [KonataDev/Lagrange.Core#238]
### Lagrange项目

OneBot

### 新需求内容

在使用lagrange onebot后，在群内被踢出时日志中没有具体的踢出事件（如在xx时间被xx用户踢出），如果可以的话希望能够增加完善一下这部分事件，感谢...!
![ed4b221590865a14d5023bc6eaef6099](https://github.com/KonataDev/Lagrange.Core/assets/162562599/c757d1e3-4013-4e32-96e9-3f71b20f4d2a)

**Comment by Linwenxuan05** [comment]
请说明你需要的完整字段
