### ISSUE TITLE
[Bug?]: Linux系统发送图片路径目录名含有中文时失败

### ISSUE THREAD

**Issue by Xiangze-Li** [KonataDev/Lagrange.Core#240]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

661ec28

### 运行环境

Linux

### 运行架构

x64

### 连接方式

正向 WebSocket

### 重现步骤

通过 CQ 码发送一张**路径的目录**中含有中文的图片

### 期望的结果是什么？

能够发送

### 实际的结果是什么？

不能发送，日志无记录

**Comment by DarkCWK** [comment]
```json
{
    "action": "send_group_msg",
    "params":{
        "group_id":0,
        "message":"[CQ:image,file=file:///home/darkcwk/中文路径/1.jpg]"
    }
}
```
Debian 12 x64 实体机复现失败

**Comment by synodriver** [comment]
试试convmv -f gbk -t utf-8 -r --notest 你的路径

**Comment by Xiangze-Li** [comment]
我在拉取 882e0b7 对应的 release 后此问题不再复现。感谢开发者关注。
