### ISSUE TITLE
[Bug?]: 当websocket连接出现错误时，会无延时重连

### ISSUE THREAD

**Issue by lliioollcn** [KonataDev/Lagrange.Core#253]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

db45b79df46af4541a98760f5231491888de6412

### 运行环境

Windows

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

连接一个端口占用/出错的ws服务器

### 期望的结果是什么？

出错后等待 ReconnectInterval 配置的时间后重连

### 实际的结果是什么？

无延时一直重连刷屏

**Comment by CrackTC** [comment]
closed in #279

**Comment by Linwenxuan05** [comment]
https://github.com/KonataDev/Lagrange.Core/commit/95612539a6e3963d29ca72b43c9ec613c0b5f41d
