### ISSUE TITLE
[Bug?]: 新版本上传图片失败

### ISSUE THREAD

**Issue by ikechan8370** [KonataDev/Lagrange.Core#262]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

b1530d0

### 运行环境

Linux

### 运行架构

x64

### 连接方式

正向 WebSocket

### 重现步骤

在 b1530d0 之后的版本 私聊和群聊上传图片必定失败。 用之前的版本就不会失败 能正常发
![image](https://github.com/KonataDev/Lagrange.Core/assets/21212372/af7a82cb-0a2a-476b-bed4-3338d3814af5)
debug下日志也没有其他信息了

### 期望的结果是什么？

能够发送图片

### 实际的结果是什么？

发出来的消息无法查看，日志里highway上传图片错误

**Comment by Linwenxuan05** [comment]
我只能提供一个可配置项到里面 因为这个pr还修复了腾讯云用户上传不了的问题

**Comment by ikechan8370** [comment]
好好好。
