### ISSUE TITLE
[Bug]: 获取群历史消息 message_id 依旧不正确

### ISSUE THREAD

**Issue by Stapxs** [KonataDev/Lagrange.Core#265]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

62f48c224a683f4721f1c94f58df5468663ac9d1

### 运行环境

Linux

### 运行架构

arm64

### 连接方式

正向 WebSocket

### 重现步骤

相关 issue：#244

- 首先用另一个账号在群中发送一条消息并同时回复这条消息：
  <img width="1184" alt="image" src="https://github.com/KonataDev/Lagrange.Core/assets/42486439/0e5bc0b6-fe0e-4f8c-b70a-e3fc21fadf91">
  如果没有意外，可以获得这两条消息并且第二条消息的 reply 段指向第一条消息
- 接下来获取历史消息列表并找到这两条消息，参考消息：
  ~~~
  {
      "action":"get_group_msg_history",
      "params":{
          "group_id":33*****68,
          "message_id":0,
          "count":20
      },
      "echo":"getChatHistoryFist"
  }
  ~~~
  <img width="1176" alt="image" src="https://github.com/KonataDev/Lagrange.Core/assets/42486439/797c92bc-0a03-4869-bc4b-a179b68e8d7b">
  发现被回复的这条消息的消息 ID 并不正确……

### 期望的结果是什么？

返回正确的消息 ID

### 实际的结果是什么？

消息 ID 不正确

**Comment by lava081** [comment]
count参数的行为好像也不符合预期，count为0时返回了1条消息，count为1时返回了2条消息

**Comment by DarkCWK** [comment]
这个 api 是向 tx 的服务器获取的消息
tx 返回的包里面缺少一个用于计算 MessageId 的数据, 所以 MessageId 不正确

**Comment by Stapxs** [comment]
> 这个 api 是向 tx 的服务器获取的消息 tx 返回的包里面缺少一个用于计算 MessageId 的数据, 所以 MessageId 不正确

感觉无解诶（瘫
