### ISSUE TITLE
[Bug?]: 私聊`get_msg`获取的`sender`详情缺失

### ISSUE THREAD

**Issue by lava081** [KonataDev/Lagrange.Core#271]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

42574843c4d66176fe78d800784514c66a749701

### 运行环境

Linux

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

通过`get_msg`获取任意一条私聊消息的详情

### 期望的结果是什么？

```
{
  "time":1711987745,
  "message_type":"private",
  "message_id":-2112981208,
  "real_id":-2112981208,
  "sender":{
    "user_id":1902688707,
    "nickname":"岩浆",
    "sex":"unknown"
  },
  "message":[
    {
      "type":"text",
      "data":{
        "text":"喵一个"
      }
    }
  ]
}
```

### 实际的结果是什么？

```
{
  "time":1711987745,
  "message_type":"private",
  "message_id":-2112981208,
  "real_id":-2112981208,
  "sender":{
    "user_id":0,
    "nickname":"",
    "sex":"unknown"
  },
  "message":[
    {
      "type":"text",
      "data":{
        "text":"喵一个"
      }
    }
  ]
}
```

**Comment by DarkCWK** [comment]
ref #220

**Comment by lava081** [comment]
变成直接报错了
