### ISSUE TITLE
[Bug]: 对机器人私聊自发消息`get_msg`，获取到的sender为私聊对象而非机器人自身

### ISSUE THREAD

**Issue by lava081** [KonataDev/Lagrange.Core#276]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

faabfa72a2ca6dfe1961005b786bef7ccc96f338

### 运行环境

Linux

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

对`send_private_msg`返回的`message_id`使用`get_msg`，

### 期望的结果是什么？

```
{
  ...
  "sender":{
    "user_id":机器人uin,
    "nickname":"机器人nickname",
    "sex":"unknown"
  },
  ...
}
```

### 实际的结果是什么？

```
{
  ...
  "sender":{
    "user_id":私聊对象的user_id,
    "nickname":"私聊对象的nickname",
    "sex":"unknown"
  },
  ...
}
```

### 简单的复现代码/链接（可选）

```C#
get_msg：{"message_id":726640341}
```

### 补充说明（可选）

[DarkCWK](https://github.com/KonataDev/Lagrange.Core/commits?author=DarkCWK)：
找lwx
他没改 chain.FriendUin
我怀疑也没改 GroupUin
FriendInfo
GroupMemberInfo
这些

**Comment by lava081** [comment]
@Linwenxuan05

**Comment by DarkCWK** [comment]
应该是 #260 没有修好
