### ISSUE TITLE
[Bug?]: 反向连接TRSS云崽时反复重连并报错

### ISSUE THREAD

**Issue by JerryYTech** [KonataDev/Lagrange.Core#286]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

ReverseWSService

### 运行环境

Windows

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

启动Lagrange.OneBot.exe
启动Redis
启动yunzai

### 期望的结果是什么？

yunzai正常连接Lagrange.OneBot并持续运行

### 实际的结果是什么？

连接不到一毫秒后断开连接，并在大约半秒后重复连接断连

### 简单的复现代码/链接（可选）

```C#
warn: Lagrange.OneBot.Core.Network.Service.ReverseWSService[3]
      [ReverseWSService] Client disconnected
      System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
...
```

### 补充说明（可选）

完整截图：
![image](https://github.com/KonataDev/Lagrange.Core/assets/129190939/d212c3f7-889d-4d67-b5c6-8a0216ceb496)
yunzai无报错：
![image](https://github.com/KonataDev/Lagrange.Core/assets/129190939/c6b07848-a4bd-4aed-bdff-2ad37c00275f)

**Comment by KusaGumina** [comment]
从lgr这边的log看，是yunzai那边关闭了链接，但云崽这边我没有看到相关的日志之类的，我建议你排查一下云崽的问题

**Comment by JerryYTech** [comment]
好的谢谢

**Comment by a1375625918** [comment]
如果启动 TRSS-Yunzai 的时候曾打印： 
```
[WebSocket] 连接地址：ws://localhost:2536/[ComWeChat,GSUIDCore,OPQBot,OneBotv11,go-cqhttp]
```
这么一行，那为 Lagrange `appsettings.json` 设置反向 WebSocket 连接后缀 `"Suffix": "/OneBotv11"` 而不是 `"/OneBot/v11/ws"` 或许能帮到你。

**Comment by JerryYTech** [comment]
一开始还没注意到。。谢谢
