### ISSUE TITLE
[Bug?]: Wrong multimsg display

### ISSUE THREAD

**Issue by Chzxxuanzheng** [KonataDev/Lagrange.Core#287]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

#281

### 运行环境

Linux

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

将一组图片进行合并发送

###### PC
![}(C%S@PNKN_ $UA5(UEJ(Q5](https://github.com/KonataDev/Lagrange.Core/assets/122149478/0d3432ce-f690-4a39-933a-73497560d01c)
###### 安卓
![QQ图片20240405020403](https://github.com/KonataDev/Lagrange.Core/assets/122149478/cbe66edc-5d55-441e-b2eb-a9e1fa68a81d)

##### 出现超时错误时
不发送信息

### 实际的结果是什么？

# 合并消息显示异常

## PC端显示
这是我使用bot发送的合并转发
![L$DB(QS1DM12EN1TRE{8@PV](https://github.com/KonataDev/Lagrange.Core/assets/122149478/9efa1a5e-628f-4305-97e6-7bb02f8e325a)
正常情况下应该会显示4条预览,而非三条,预览内容应该为`名称:[图片]`而非`名称:`

## 安卓端显示
![0940951ed5a751303ff05b1143931ef9](https://github.com/KonataDev/Lagrange.Core/assets/122149478/d137ed04-3d9f-43e0-adab-db2f93f5a608)
第一个3条消息是
`WebSocket call api send_private_forward_msg timeout`得到的不正常的消息
第二个是拥有50张图的消息

### 简单的复现代码/链接（可选）

```C#
from nonebot.adapters.onebot.v11 import Bot, GroupMessageEvent, PrivateMessageEvent
from nonebot.typing import T_State
from nonebot.matcher import Matcher
from nonebot.adapters.onebot.v11 import NetworkError, MessageSegment
from nonebot.log import logger

#发送图片
async def sendListMessage(messageList: list[MessageSegment], config: T_State):
	bot: Bot = config['bot']
	event: GroupMessageEvent|PrivateMessageEvent = config['event']
	sender: Matcher= config['self']
	# logger.log(str(messageList[0]))
	#单独发
	if len(messageList) <= 3:
		for i in messageList:
			await sender.send(i)
	#打包成合并转发
	else:
		msgs = [
			{
			'type':'node',
			'data':{
				'nickname':"Flandre Scarlet",
				'user_id':bot.self_id,
				'content':i,
				},
			}
			for i in messageList
		]
		try:
			#群
			if isinstance(event, GroupMessageEvent):
				await bot.call_api("send_group_forward_msg",group_id = event.group_id,messages = msgs)
			#私聊
			else:
				await bot.call_api("send_private_forward_msg",user_id=event.user_id,messages=msgs)
		except NetworkError as ex:
			logger.error(ex.msg)
```

### 补充说明（可选）

个人感觉`WebSocket call api send_private_forward_msg timeout`产生的不正常消息不应该被发送

**Comment by CrackTC** [comment]
> 个人感觉`WebSocket call api send_private_forward_msg timeout`产生的不正常消息不应该被发送

这个应该是等待`echo`超时，没办法取消
