### ISSUE TITLE
[Bug?]: 不接收语言消息

### ISSUE THREAD

**Issue by xiaomujin** [KonataDev/Lagrange.Core#291]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

https://github.com/KonataDev/Lagrange.Core/commit/633efc55ebe08d87ebe6991ae9aed5871dd09b2d

### 运行环境

Linux

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

发送语音消息就行 onebot没有反应

### 期望的结果是什么？

有输出和事件推送

### 实际的结果是什么？

没有输出和事件推送

**Comment by jhqwqmc** [comment]
这个问题貌似重新出现了

**Comment by pk5ls20** [comment]
日志呢

**Comment by jhqwqmc** [comment]
> 日志呢

没有任何的输出
