### ISSUE TITLE
[Bug?]: 合并转发里的uin是str类型的吗?  gocq之前的是int类型

### ISSUE THREAD

**Issue by dabao52099** [KonataDev/Lagrange.Core#310]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

Audio

### 所使用/依赖的Lagrange项目对应的commit

1

### 运行环境

Windows

### 运行架构

x64

### 连接方式

None

### 重现步骤

node里的 uin实际是str类型 文档里写的是int

### 期望的结果是什么？

修复bug ,拉个蓝文档里写的也是int类型呢 实际确实只支持str类型

### 实际的结果是什么？

修复bug ,拉个蓝文档里写的也是int类型呢 实际确实只支持str类型

**Comment by ishkong** [comment]
合并转发中uin是str，gocq之前是int和str都支持，gocq文档里的example里是str，lgr文档Node Segment中uin已修改为string，onebot规范中是str，原因：为了更好的兼容cqcode （坏！
