### ISSUE TITLE
[Bug?]: 合并转发uin与nickename错误

### ISSUE THREAD

**Issue by Chzxxuanzheng** [KonataDev/Lagrange.Core#313]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

5369aaaa4f554c76fb5672ef6975d96c9b52854e

### 运行环境

Linux

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

使用合并转发,发送非bot的nickname和user_id

### 期望的结果是什么？

打开合并转发后,显示的nickname和头像应该和发送的nickname和user_id相照应

### 实际的结果是什么？

nickname和头像全都是bot的

### 简单的复现代码/链接（可选）

```C#
async def sendMsg(config: T_State, msg):
	if type(msg) == str:
		msg = MessageSegment.text(msg)
	bot: Bot = config['bot']
	event: Event = config['event']
	try:
		#群
		if isinstance(event, GroupMessageEvent):
			await bot.call_api("send_group_msg",group_id = event.group_id,message=msg)
		#私聊
		else:
			await bot.call_api("send_private_msg",user_id=event.user_id,message=msg)
	except NetworkError as ex:
		logger.error(ex.msg)
	except Exception as ex:
		logger.error(ex)
```

**Comment by Linwenxuan05** [comment]
来自腾讯的Bug 没救

**Comment by snowykami** [comment]
逆天，刚好也遇到这个问题了

**Comment by qllokirin** [comment]
+1 同样的调用在gocq能正常显示名称和头像，拉格朗的名称是bot的然后头绪是默认头像
