### ISSUE TITLE
[Bug]:linux arm版本无法登陆 

### ISSUE THREAD

**Issue by mengluo04** [KonataDev/Lagrange.Core#322]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

 bc2241d  

### 运行环境

Linux

### 运行架构

arm

### 连接方式

反向 WebSocket

### 重现步骤

1.在release页面下载最新的[Lagrange.OneBot_linux-arm_8.0.zip](https://github.com/KonataDev/Lagrange.Core/releases/download/nightly/Lagrange.OneBot_linux-arm_8.0.zip)
2.在树莓派的Ubuntu系统和机顶盒的海纳思系统（Ubuntu）上使用unzip解压得到publish文件夹
3.使用chmod 777  Lagrange.OneBot设置权限
4.使用./ Lagrange.OneBot执行
5.生成配置文件后再次执行

### 期望的结果是什么？

能正确出现登陆二维码

### 实际的结果是什么？

报错，连接不到qq的服务器
这是树莓派上错误信息
![image](https://github.com/KonataDev/Lagrange.Core/assets/32565940/0a135594-a995-47c5-819f-fdb6867dcdb5)
这是机顶盒里面Ubuntu的错误信息
![image](https://github.com/KonataDev/Lagrange.Core/assets/32565940/b44697c6-28d4-4513-bad6-7b6e1d841769)
这是windows下正确的输出信息，x86架构的64位Linux云服务器上也是相同显示
![image](https://github.com/KonataDev/Lagrange.Core/assets/32565940/bc1af4c4-2fc1-47d7-aa17-72df6712abd3)

**Comment by CrackTC** [comment]
duplicate to #247
