### ISSUE TITLE
[Bug?]: [at:qq=0]问题

### ISSUE THREAD

**Issue by xin-code** [KonataDev/Lagrange.Core#329]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

Core

### 所使用/依赖的Lagrange项目对应的commit

7fa1d6af07b6cc84083443e3bbbc08274e4235c3

### 运行环境

Linux

### 运行架构

x64

### 连接方式

正向 WebSocket

### 重现步骤

0|Lagrange.OneBot  | info: Lagrange.Core.BotContext[0]
0|Lagrange.OneBot  |       [2024-04-24 14:25:02] [MessagingLogic] [VERBOSE]: [MessageChain(QQ群)(用户)] [Mention]: @BOT(0)
0|Lagrange.OneBot  | trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
0|Lagrange.OneBot  |       [ReverseWSService] Send: {"message_type":"group","sub_type":"normal","message_id":-1005846739,"group_id":QQ群,"user_id":用户,"anonymous":null,"message":[{"type":"at","data":{"qq":"0"}}],"raw_message":"[CQ:at,qq=0]","font":0,"sender":{"user_id":用户,"nickname":"用户昵称","card":"群组名片","sex":"unknown","age":0,"area":"","level":"93","role":"owner","title":""},"time":1713939902,"self_id":BOT的qq号,"post_type":"message"}
0|Lagrange.OneBot  | trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[2]
0|Lagrange.OneBot  |       [ReverseWSService] Receive: {"action": "get_group_member_info", "params": {"group_id": QQ群, "user_id": "0"}, "echo": "64"}
0|Lagrange.OneBot  | trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
0|Lagrange.OneBot  |       [ReverseWSService] Send: {"status":"failed","retcode":-1,"data":null,"echo":"64"}
0|Lagrange.OneBot  | trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[2]
0|Lagrange.OneBot  |       [ReverseWSService] Receive: {"action": "send_group_msg", "params": {"group_id": QQ群, "message": "[CQ:at,qq=0]", "auto_escape": false}, "echo": "65"}

### 期望的结果是什么？

@用户可以获取到qq号

### 实际的结果是什么？

[at:qq=0]

### 补充说明（可选）

release版本
Ubuntu Server 22.04 LTS 64bit 下载使用也是同样的问题
在Windows10 x64  版本19045.4291 也会出现这个问题
尝试安装.NET 8 最新的action中下载 commit为393e7f0ff6173844acf073d3ba6feccebdbcaae7 这个的win 也是这样
![123](https://github.com/KonataDev/Lagrange.Core/assets/32591789/e0ee70ff-b070-45bb-bd34-b2921be83d23)

**Comment by DarkCWK** [comment]
未能在 WIndows 11 下使用最新 (5f04dde527cb1f0c4b95db6f72d03e634e6a84d4) 和 393e7f0ff6173844acf073d3ba6feccebdbcaae7 复现

**Comment by eggggi** [comment]
qq问题，用新版qq就行了

**Comment by xin-code** [comment]
> qq问题，用新版qq就行了

请问如何更新，我这好像没找到相关的配置项

**Comment by xin-code** [comment]
复现出来问题了
1、手机版@机器人或者别人，能够接收到QQ号，，没问题
2、QQNT版本发送@指令，能够接收到QQ号，没问题
3、只要通过Windows客户端(不是NT版本)下@qq机器人或者别人的话，在启动的Lagrange内就会出现[at:qq=0]的情况。
下面是两个qq版本发送@指令后就不能在Lagrange内获取到qq的情况
![QQ截图20240425174623](https://github.com/KonataDev/Lagrange.Core/assets/32591789/ff715a0e-5ece-4ff1-8a66-9438989e2326)
![1](https://github.com/KonataDev/Lagrange.Core/assets/32591789/930ae16b-5367-430c-8559-a30d5a0d2853)

**Comment by Lioncky** [comment]
该版本也没有@ID
![image](https://github.com/KonataDev/Lagrange.Core/assets/73447685/38ffd380-495f-4ae3-ac92-c2e5fdad42fe)

**Comment by DarkCWK** [comment]
> 用3月23日打包的 就有艾特ID了

可以说说具体是哪个 commit 开始不行的么？
