### ISSUE TITLE
[Bug?]: 发送图片时 summary 字段不生效

### ISSUE THREAD

**Issue by xiaomujin** [KonataDev/Lagrange.Core#331]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

https://github.com/KonataDev/Lagrange.Core/commit/f63c0060468136eeb142ea00d030e872a1046683

### 运行环境

Windows

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

```json
{"action":"send_group_msg","echo":0,"params":{"group_id":571632659,"message":[{"data":{"summary":"看看猫","file":"https://img3.saucenao.com/dA/96/968332.jpg?auth=DSf6zi3gE2rSoqWdz6-9Dw&exp=1714503600"},"rowType":"image","type":"image"}],"auto_escape":false}}
```

### 期望的结果是什么？

![image](https://github.com/KonataDev/Lagrange.Core/assets/38455940/88012818-dcf9-4f66-b14d-e7026deb8bf2)
显示 summary 字段的文本

### 实际的结果是什么？

显示 [图片]

### 补充说明（可选）

![image](https://github.com/KonataDev/Lagrange.Core/assets/38455940/170c19b6-eee0-40ec-816c-f82778190a31)
![image](https://github.com/KonataDev/Lagrange.Core/assets/38455940/93b4e94e-482c-42ba-b5ed-3a07e08cdc77)

**Comment by xiaomujin** [comment]
> 目前没有实现 Image 的 Summary 的发送

有计划支持嘛

**Comment by DarkCWK** [comment]
> 有计划支持嘛
@CrackTC 目前正在支持 #332

**Comment by CrackTC** [comment]
试了一下,NT可以显示自定义的Summary,老版本PC客户端好像不行
