### ISSUE TITLE
[Feature Request]: option for remove 'message' field

### ISSUE THREAD

**Issue by Lioncky** [KonataDev/Lagrange.Core#333]
### Lagrange项目

Core

### 新需求内容

The 'row_message' has alreadly existed and someone like me don't need message field , it takes more time for json parser.
I removed it by my code in backend, and want have an option to ban it for boost the Core faster.
```
					// remove 'message' field
					{
						char* p; size_t l, last, first = message.find(R"("message":[{)");
						if (first != std::string::npos) {
							p = message.data();
							last = message.find(R"("raw_message":)", first);

							// remove 
							l = strlen(p + last);
							memcpy(p + first, p + last, l + 1);
							message.resize(first + l);
						}
					}
```

**Comment by DarkCWK** [comment]
This field is a standard field in onebot-11
Maybe you need to raise an issue at https://github.com/botuniverse/onebot-11

**Comment by Lioncky** [comment]
> This field is a standard field in onebot-11 Maybe you need to raise an issue at https://github.com/botuniverse/onebot-11

I known it's in one v11 but I just want it, little problem.
