### ISSUE TITLE
[Bug?]: 快速操作没有效果

### ISSUE THREAD

**Issue by tpa-wy** [KonataDev/Lagrange.Core#337]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

bc2241d

### 运行环境

MacOS

### 运行架构

arm64

### 连接方式

HTTP

### 重现步骤

我是mac不知道是否支持快捷操作 仔细的阅读文档发现跳转的是onebot的文档说明

### 期望的结果是什么？

可以按照onebot的文档一样
可以快速操作如快速回复、快速禁言等

### 实际的结果是什么？

没有发送消息 只能调用api发送消息

### 简单的复现代码/链接（可选）

```C#
$data = [];
        $data["reply"] = "嗨～";
        // {
        //     "reply": "晚安，妈了个巴子"
        // }
        return response()->json($data);
```

**Comment by Linwenxuan05** [comment]
尚未支持快速操作
